n = (input('Digite algo: '))
print('O tipo primitivo é: ', type(n))
print('é alfanumérico? /', n.isalnum())
print('é alfabético? /', n.isalpha())
print('está somente com maiúsculas? /', n.isupper())
print('está somente em minúsculas? /', n.islower())
print('pode ser impresso? /', n.isprintable())
print('é um decimal? /', n.isdecimal())
print('isdigit /', n.isdigit())
print('isidentifier /', n.isidentifier())
print('isspace /', n.isspace())
print('Está capitalizada? /', n.istitle())
